export const moodColors = [
    { mood: "Happy", color: "Yellow", hex: "#FFD700" },
    { mood: "Sad", color: "Blue", hex: "#1E90FF" },
    { mood: "Calm", color: "Green", hex: "#32CD32" },
    { mood: "Energetic", color: "Orange", hex: "#FF8C00" },
    { mood: "Passionate", color: "Red", hex: "#FF4500" },
    { mood: "Creative", color: "Purple", hex: "#8A2BE2" },
    { mood: "Relaxed", color: "Light Blue", hex: "#ADD8E6" },
    { mood: "Focused", color: "Dark Blue", hex: "#00008B" },
    { mood: "Excited", color: "Magenta", hex: "#FF00FF" },
    { mood: "Tense", color: "Gray", hex: "#808080" },
    { mood: "Romantic", color: "Pink", hex: "#FF69B4" },
    { mood: "Anxious", color: "Brown", hex: "#A52A2A" },
    { mood: "Optimistic", color: "Light Green", hex: "#90EE90" },
    { mood: "Bored", color: "Beige", hex: "#F5F5DC" },
    { mood: "Confident", color: "Gold", hex: "#FFD700" },
    { mood: "Surprised", color: "Turquoise", hex: "#40E0D0" },
    { mood: "Grateful", color: "Lavender", hex: "#E6E6FA" },
    { mood: "Hopeful", color: "Teal", hex: "#008080" },
    { mood: "Lonely", color: "Navy", hex: "#000080" },
    { mood: "Motivated", color: "Cyan", hex: "#00FFFF" },
    { mood: "Curious", color: "Peach", hex: "#FFDAB9" },
    { mood: "Disappointed", color: "Dark Gray", hex: "#A9A9A9" },
    { mood: "Frustrated", color: "Brick Red", hex: "#B22222" },
    { mood: "Jealous", color: "Olive", hex: "#808000" },
    { mood: "Insecure", color: "Light Gray", hex: "#D3D3D3" },
    { mood: "Nostalgic", color: "Sepia", hex: "#704214" },
    { mood: "Adventurous", color: "Forest Green", hex: "#228B22" },
    { mood: "Grumpy", color: "Dark Red", hex: "#8B0000" },
    { mood: "Peaceful", color: "Light Lavender", hex: "#E6E6FA" },
    { mood: "Melancholic", color: "Slate Blue", hex: "#6A5ACD" },
    { mood: "Determined", color: "Steel Blue", hex: "#4682B4" },
    { mood: "Overwhelmed", color: "Charcoal", hex: "#36454F" },
    { mood: "Vulnerable", color: "Pale Pink", hex: "#FFB6C1" },
    { mood: "Resentful", color: "Maroon", hex: "#800000" },
    { mood: "Skeptical", color: "Olive Drab", hex: "#6B8E23" },
    { mood: "Triumphant", color: "Crimson", hex: "#DC143C" },
    { mood: "Humorous", color: "Lemon", hex: "#FFFACD" },
    { mood: "Curious", color: "Coral", hex: "#FF7F50" },
    { mood: "Affectionate", color: "Blush", hex: "#FFB6C1" },
    { mood: "Fearful", color: "Midnight Blue", hex: "#191970" },
    { mood: "Playful", color: "Violet", hex: "#EE82EE" },
    { mood: "Doubtful", color: "Dark Slate Gray", hex: "#2F4F4F" },
    { mood: "Empathetic", color: "Light Coral", hex: "#F08080" },
    { mood: "Pessimistic", color: "Dark Olive Green", hex: "#556B2F" },
    { mood: "Conflicted", color: "Copper", hex: "#B87333" },
    { mood: "Lonely", color: "Indigo", hex: "#4B0082" },
    { mood: "Proud", color: "Amber", hex: "#FFBF00" },
    { mood: "Euphoric", color: "Bright Pink", hex: "#FF007F" },
    { mood: "Ashamed", color: "Muted Brown", hex: "#8B4513" },
    { mood: "Awestruck", color: "Electric Blue", hex: "#7DF9FF" },
    { mood: "Lethargic", color: "Pale Green", hex: "#98FB98" },
    { mood: "Generous", color: "Rose", hex: "#FF007F" },
    { mood: "Blissful", color: "Sunset Orange", hex: "#FF4500" },
];
